# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bigdecimal'
gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'puma'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'ulid'
gem 'json'
gem 'activesupport', require: 'active_support/all'
